/* ANNOTATION_BLOCK_START
{
  "artifact_id": "cycle0_mock_data_recipes_g112",
  "version_tag": "0.1.0",
  "g_created": 125,
  "g_last_modified": 125,
  "description": "Provides mock data for recipes to be used throughout the web prototype. This allows for UI development and testing without a live backend.",
  "artifact_type": "JSON_DATA_FILE", 
  "status_in_lifecycle": "DEVELOPMENT",
  "purpose_statement": "To supply a standardized set of recipe data for populating components and pages in the prototype, facilitating consistent testing and demonstration of recipe-related features.",
  "key_logic_points": [
    "Contains an array of recipe objects.",
    "Each recipe object includes fields like id, name, description, ingredients, instructions, image URLs, creator information, ratings, etc.",
    "Data should be diverse enough to represent various recipe types and complexities."
  ],
  "interfaces_provided": [
    { "name": "mockRecipes", "interface_type": "JAVASCRIPT_ARRAY", "details": "An array of JavaScript objects, where each object represents a recipe.", "notes": "Exported as a const." }
  ],
  "requisites": [],
  "external_dependencies": [],
  "internal_dependencies": [], 
  "dependents": [
    "cycle0_page_home_g112",
    "cycle0_page_recipedetail_g112",
    "cycle0_page_mealplan_g112",
    "cycle0_page_userprofile_g112",
    "cycle0_page_creatorprofile_g112",
    "cycle0_mock_services_g112" 
  ],
  "linked_issue_ids": [],
  "quality_notes": {
    "unit_tests": "N/A",
    "manual_review_comment": "Initial scaffold by Hybrid_AI_OS g125. Contains a sample set of mock recipes. More detailed and varied data can be added as needed."
  }
}
ANNOTATION_BLOCK_END */

export const mockRecipes = [
  {
    id: 'r1',
    name: 'Spicy Chicken Pasta',
    description: 'A quick and delicious pasta dish with a spicy kick, perfect for a weeknight meal. Packed with flavor and easy to customize.',
    cuisine: 'Italian-American',
    difficulty: 'Easy',
    prepTime: '15 mins',
    cookTime: '20 mins',
    servings: 4,
    tags: ['pasta', 'chicken', 'spicy', 'quick meal'],
    imageUrl: 'https://via.placeholder.com/600x400?text=Spicy+Chicken+Pasta',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Spicy+Pasta',
    ingredients: [
      { name: 'Chicken Breast', quantity: '2', unit: 'large', notes: 'cut into 1-inch pieces' },
      { name: 'Penne Pasta', quantity: '400', unit: 'g' },
      { name: 'Olive Oil', quantity: '2', unit: 'tbsp' },
      { name: 'Onion', quantity: '1', unit: 'medium', notes: 'chopped' },
      { name: 'Garlic', quantity: '3', unit: 'cloves', notes: 'minced' },
      { name: 'Red Pepper Flakes', quantity: '1', unit: 'tsp', notes: 'or to taste' },
      { name: 'Diced Tomatoes', quantity: '1', unit: 'can (400g)' },
      { name: 'Heavy Cream', quantity: '1/2', unit: 'cup' },
      { name: 'Parmesan Cheese', quantity: '1/4', unit: 'cup', notes: 'grated, plus more for serving' },
      { name: 'Fresh Parsley', quantity: '2', unit: 'tbsp', notes: 'chopped, for garnish' },
      { name: 'Salt and Pepper', quantity: 'to', unit: 'taste' },
    ],
    instructions: [
      'Cook pasta according to package directions. Drain and set aside.',
      'While pasta cooks, heat olive oil in a large skillet over medium heat. Add chicken and cook until browned and cooked through. Remove chicken and set aside.',
      'Add onion to the skillet and cook until softened, about 5 minutes. Add garlic and red pepper flakes and cook for 1 minute more until fragrant.',
      'Stir in diced tomatoes and bring to a simmer. Reduce heat and cook for 5-7 minutes, allowing sauce to thicken slightly.',
      'Stir in heavy cream and Parmesan cheese. Season with salt and pepper to taste.',
      'Return cooked chicken and pasta to the skillet. Toss to combine and heat through.',
      'Serve immediately, garnished with fresh parsley and extra Parmesan cheese if desired.',
    ],
    rating: 4.5,
    reviewsCount: 120,
    creatorId: 'c1', // Corresponds to mockCreators id
    creatorName: 'Chef Gourmet Master',
    dateAdded: '2023-10-01',
    nutrition: {
      calories: '550 kcal',
      protein: '35g',
      fat: '25g',
      carbs: '45g',
    },
  },
  {
    id: 'r2',
    name: 'Vegan Buddha Bowl',
    description: 'A vibrant and nutritious vegan Buddha bowl packed with roasted vegetables, quinoa, and a creamy tahini dressing.',
    cuisine: 'Vegan',
    difficulty: 'Medium',
    prepTime: '25 mins',
    cookTime: '30 mins',
    servings: 2,
    tags: ['vegan', 'healthy', 'bowl', 'quinoa', 'vegetables'],
    imageUrl: 'https://via.placeholder.com/600x400?text=Vegan+Buddha+Bowl',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Buddha+Bowl',
    ingredients: [
      { name: 'Quinoa', quantity: '1', unit: 'cup', notes: 'rinsed' },
      { name: 'Sweet Potato', quantity: '1', unit: 'large', notes: 'peeled and diced' },
      { name: 'Broccoli Florets', quantity: '2', unit: 'cups' },
      { name: 'Chickpeas', quantity: '1', unit: 'can (400g)', notes: 'rinsed and drained' },
      { name: 'Olive Oil', quantity: '2', unit: 'tbsp' },
      { name: 'Smoked Paprika', quantity: '1', unit: 'tsp' },
      { name: 'Cumin Powder', quantity: '1/2', unit: 'tsp' },
      { name: 'Tahini', quantity: '1/4', unit: 'cup' },
      { name: 'Lemon Juice', quantity: '2', unit: 'tbsp' },
      { name: 'Maple Syrup', quantity: '1', unit: 'tbsp' },
      { name: 'Water', quantity: '2-3', unit: 'tbsp', notes: 'for dressing consistency' },
      { name: 'Sesame Seeds', quantity: '1', unit: 'tbsp', notes: 'for garnish' },
      { name: 'Salt and Pepper', quantity: 'to', unit: 'taste' },
    ],
    instructions: [
      'Preheat oven to 200°C (400°F). Cook quinoa according to package directions.',
      'On a baking sheet, toss sweet potato and broccoli with 1 tbsp olive oil, paprika, cumin, salt, and pepper. Roast for 20-25 minutes, or until tender and slightly caramelized.',
      'In a small bowl, whisk together tahini, lemon juice, maple syrup, and water until smooth. Season with salt to taste.',
      'To assemble the bowls, divide cooked quinoa between two bowls. Top with roasted vegetables and chickpeas.',
      'Drizzle with tahini dressing and garnish with sesame seeds. Serve warm or at room temperature.',
    ],
    rating: 4.8,
    reviewsCount: 95,
    creatorId: 'c2',
    creatorName: 'Healthy Bites Ella',
    dateAdded: '2023-11-15',
    nutrition: {
      calories: '480 kcal',
      protein: '20g',
      fat: '22g',
      carbs: '55g',
    },
  },
  {
    id: 'r3',
    name: 'Classic Berry Smoothie',
    description: 'A refreshing and healthy smoothie packed with mixed berries, banana, and yogurt. Perfect for breakfast or a quick snack.',
    cuisine: 'Healthy',
    difficulty: 'Easy',
    prepTime: '5 mins',
    cookTime: '0 mins',
    servings: 1,
    tags: ['smoothie', 'berry', 'healthy', 'breakfast', 'quick'],
    imageUrl: 'https://via.placeholder.com/600x400?text=Berry+Smoothie',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Smoothie',
    ingredients: [
      { name: 'Mixed Berries', quantity: '1', unit: 'cup', notes: 'frozen (e.g., strawberries, blueberries, raspberries)' },
      { name: 'Banana', quantity: '1/2', unit: '', notes: 'ripe, preferably frozen' },
      { name: 'Greek Yogurt', quantity: '1/2', unit: 'cup', notes: 'plain or vanilla' },
      { name: 'Milk', quantity: '1/2', unit: 'cup', notes: 'or almond milk, soy milk' },
      { name: 'Honey or Maple Syrup', quantity: '1', unit: 'tsp', notes: 'optional, to taste' },
    ],
    instructions: [
      'Combine all ingredients in a blender.',
      'Blend until smooth and creamy. Add more milk if a thinner consistency is desired.',
      'Taste and add sweetener if needed.',
      'Pour into a glass and serve immediately.',
    ],
    rating: 4.6,
    reviewsCount: 210,
    creatorId: 'c2',
    creatorName: 'Healthy Bites Ella',
    dateAdded: '2023-09-20',
     nutrition: {
      calories: '250 kcal',
      protein: '15g',
      fat: '5g',
      carbs: '40g',
    },
  }
  // Add more recipe objects here to make the prototype more engaging
]; 